services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "rm -f /opt/app/tmp/pids/server.pid && 
             bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_DEVELOPMENT}
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data: {}
