# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

test:
  <<: *default
  database: im_back_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['DB_NAME_PRODUCTION'] %>
  cache:
    <<: *primary_production
    database: <%= ENV['DB_NAME_PRODUCTION_CACHE'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV['DB_NAME_PRODUCTION_QUEUE'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV['DB_NAME_PRODUCTION_CABLE'] %>
    migrations_paths: db/cable_migrate